// Vercel Function: /api/generate-signal
// Modern Node.js runtime style using Web Request/Response.
// No external libraries needed.
//
// This function:
// - Handles POST requests with JSON body: { symbol, accountSize, tradeRiskPercent }
// - Adds CORS headers so you can call it from localhost or GitHub Pages
// - Returns a simple mock trading signal + risk/position sizing

type SignalSide = 'buy' | 'sell';

interface SignalRequest {
  symbol: string;
  accountSize: number;
  tradeRiskPercent: number;
}

interface RiskInfo {
  accountSize: number;
  tradeRiskPercent: number;
  riskAmount: number;
  positionSize: number;
}

interface SignalInfo {
  symbol: string;
  side: SignalSide;
  entryType: 'market' | 'limit';
  entryPrice: number;
  stopLoss: number;
  takeProfit1: number;
  takeProfit2: number;
  timeFrame: string;
  comment: string;
}

interface SignalResponseBody {
  signal: SignalInfo;
  risk: RiskInfo;
}

// Reusable CORS headers
const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST,OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

// Handle preflight (OPTIONS) requests
export function OPTIONS() {
  return new Response(null, {
    status: 200,
    headers: CORS_HEADERS,
  });
}

// Handle the actual POST request
export async function POST(request: Request): Promise<Response> {
  try {
    const body = (await request.json()) as Partial<SignalRequest>;

    const { symbol, accountSize, tradeRiskPercent } = body;

    // Basic validation
    if (!symbol || typeof symbol !== 'string' || !symbol.trim()) {
      return json(
        { error: 'symbol is required (string)' },
        { status: 400 }
      );
    }

    if (
      typeof accountSize !== 'number' ||
      !Number.isFinite(accountSize) ||
      accountSize <= 0
    ) {
      return json(
        { error: 'accountSize must be a positive number' },
        { status: 400 }
      );
    }

    if (
      typeof tradeRiskPercent !== 'number' ||
      !Number.isFinite(tradeRiskPercent) ||
      tradeRiskPercent <= 0 ||
      tradeRiskPercent > 100
    ) {
      return json(
        { error: 'tradeRiskPercent must be between 0 and 100' },
        { status: 400 }
      );
    }

    // --- Mock signal logic (you can later replace with real AI) ---

    // Normalize symbol
    const normalizedSymbol = symbol.trim().toUpperCase();

    // Very simple fake price logic for demonstration
    const basePrice = 100; // imagine this is the current price
    const side: SignalSide = Math.random() > 0.5 ? 'buy' : 'sell';

    // Distance between entry and stop-loss
    const slDistance = basePrice * 0.01; // 1% of price
    const riskAmount = (accountSize * tradeRiskPercent) / 100;

    // Position size = riskAmount / distance to SL
    const positionSizeRaw =
      slDistance > 0 ? riskAmount / slDistance : riskAmount;
    const positionSize = Number(positionSizeRaw.toFixed(2));

    const entryPrice = basePrice;
    const stopLoss =
      side === 'buy' ? basePrice - slDistance : basePrice + slDistance;
    const takeProfit1 =
      side === 'buy'
        ? basePrice + slDistance * 1.5
        : basePrice - slDistance * 1.5;
    const takeProfit2 =
      side === 'buy'
        ? basePrice + slDistance * 3
        : basePrice - slDistance * 3;

    const responseBody: SignalResponseBody = {
      signal: {
        symbol: normalizedSymbol,
        side,
        entryType: 'market',
        entryPrice: Number(entryPrice.toFixed(2)),
        stopLoss: Number(stopLoss.toFixed(2)),
        takeProfit1: Number(takeProfit1.toFixed(2)),
        takeProfit2: Number(takeProfit2.toFixed(2)),
        timeFrame: 'H1',
        comment:
          'This is a demo signal generated by the backend. Replace this logic with AI later.',
      },
      risk: {
        accountSize,
        tradeRiskPercent,
        riskAmount: Number(riskAmount.toFixed(2)),
        positionSize,
      },
    };

    return json(responseBody, { status: 200 });
  } catch (error) {
    console.error('Error in /api/generate-signal:', error);
    return json(
      { error: 'Internal error while generating signal' },
      { status: 500 }
    );
  }
}

// Helper to return JSON with CORS headers
function json(data: unknown, init?: ResponseInit): Response {
  return new Response(JSON.stringify(data), {
    status: init?.status ?? 200,
    headers: {
      'Content-Type': 'application/json',
      ...CORS_HEADERS,
    },
  });
}
